---
kind: pipeline
type: kubernetes
name: docker-pipeline

steps:
  - name: hashiparser 
    image: plugins/docker
    settings:
      repo: cr.ittests.ru/hashiparser
      registry: cr.ittests.ru
      dockerfile: ./build/Dockerfile
      tags: ["${DRONE_COMMIT_SHA:0:7}", "latest"]
      username:
        from_secret: cr_username
      password:
        from_secret: cr_password
